// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v3.21.12
// source: fs_tree_manager.proto

package fs_tree_manager

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchReplicaRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserName      string                 `protobuf:"bytes,1,opt,name=user_name,json=userName,proto3" json:"user_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReplicaRequest) Reset() {
	*x = FetchReplicaRequest{}
	mi := &file_fs_tree_manager_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReplicaRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReplicaRequest) ProtoMessage() {}

func (x *FetchReplicaRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fs_tree_manager_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReplicaRequest.ProtoReflect.Descriptor instead.
func (*FetchReplicaRequest) Descriptor() ([]byte, []int) {
	return file_fs_tree_manager_proto_rawDescGZIP(), []int{0}
}

func (x *FetchReplicaRequest) GetUserName() string {
	if x != nil {
		return x.UserName
	}
	return ""
}

type FetchReplicaResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Tree          *MerkleTree            `protobuf:"bytes,1,opt,name=tree,proto3" json:"tree,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReplicaResponse) Reset() {
	*x = FetchReplicaResponse{}
	mi := &file_fs_tree_manager_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReplicaResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReplicaResponse) ProtoMessage() {}

func (x *FetchReplicaResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fs_tree_manager_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReplicaResponse.ProtoReflect.Descriptor instead.
func (*FetchReplicaResponse) Descriptor() ([]byte, []int) {
	return file_fs_tree_manager_proto_rawDescGZIP(), []int{1}
}

func (x *FetchReplicaResponse) GetTree() *MerkleTree {
	if x != nil {
		return x.Tree
	}
	return nil
}

type MerkleNode struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// We use the stable uuid from fs_entry so pointers to it stay valid when this
	// node is updated.
	Id            string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	MerkleHash    string   `protobuf:"bytes,2,opt,name=merkle_hash,json=merkleHash,proto3" json:"merkle_hash,omitempty"`
	ChildrenIds   []string `protobuf:"bytes,3,rep,name=children_ids,json=childrenIds,proto3" json:"children_ids,omitempty"`
	ParentId      string   `protobuf:"bytes,4,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	FsEntry       *FSEntry `protobuf:"bytes,5,opt,name=fs_entry,json=fsEntry,proto3" json:"fs_entry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleNode) Reset() {
	*x = MerkleNode{}
	mi := &file_fs_tree_manager_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleNode) ProtoMessage() {}

func (x *MerkleNode) ProtoReflect() protoreflect.Message {
	mi := &file_fs_tree_manager_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleNode.ProtoReflect.Descriptor instead.
func (*MerkleNode) Descriptor() ([]byte, []int) {
	return file_fs_tree_manager_proto_rawDescGZIP(), []int{2}
}

func (x *MerkleNode) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MerkleNode) GetMerkleHash() string {
	if x != nil {
		return x.MerkleHash
	}
	return ""
}

func (x *MerkleNode) GetChildrenIds() []string {
	if x != nil {
		return x.ChildrenIds
	}
	return nil
}

func (x *MerkleNode) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *MerkleNode) GetFsEntry() *FSEntry {
	if x != nil {
		return x.FsEntry
	}
	return nil
}

type MerkleTree struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	RootId string                 `protobuf:"bytes,1,opt,name=root_id,json=rootId,proto3" json:"root_id,omitempty"`
	// id -> node
	Nodes         map[string]*MerkleNode `protobuf:"bytes,2,rep,name=nodes,proto3" json:"nodes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MerkleTree) Reset() {
	*x = MerkleTree{}
	mi := &file_fs_tree_manager_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MerkleTree) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MerkleTree) ProtoMessage() {}

func (x *MerkleTree) ProtoReflect() protoreflect.Message {
	mi := &file_fs_tree_manager_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MerkleTree.ProtoReflect.Descriptor instead.
func (*MerkleTree) Descriptor() ([]byte, []int) {
	return file_fs_tree_manager_proto_rawDescGZIP(), []int{3}
}

func (x *MerkleTree) GetRootId() string {
	if x != nil {
		return x.RootId
	}
	return ""
}

func (x *MerkleTree) GetNodes() map[string]*MerkleNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type FSEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Metadata      *structpb.Struct       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FSEntry) Reset() {
	*x = FSEntry{}
	mi := &file_fs_tree_manager_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FSEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FSEntry) ProtoMessage() {}

func (x *FSEntry) ProtoReflect() protoreflect.Message {
	mi := &file_fs_tree_manager_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FSEntry.ProtoReflect.Descriptor instead.
func (*FSEntry) Descriptor() ([]byte, []int) {
	return file_fs_tree_manager_proto_rawDescGZIP(), []int{4}
}

func (x *FSEntry) GetMetadata() *structpb.Struct {
	if x != nil {
		return x.Metadata
	}
	return nil
}

var File_fs_tree_manager_proto protoreflect.FileDescriptor

const file_fs_tree_manager_proto_rawDesc = "" +
	"\n" +
	"\x15fs_tree_manager.proto\x12\x0ffs_tree_manager\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1bgoogle/protobuf/empty.proto\"2\n" +
	"\x13FetchReplicaRequest\x12\x1b\n" +
	"\tuser_name\x18\x01 \x01(\tR\buserName\"G\n" +
	"\x14FetchReplicaResponse\x12/\n" +
	"\x04tree\x18\x01 \x01(\v2\x1b.fs_tree_manager.MerkleTreeR\x04tree\"\xb2\x01\n" +
	"\n" +
	"MerkleNode\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vmerkle_hash\x18\x02 \x01(\tR\n" +
	"merkleHash\x12!\n" +
	"\fchildren_ids\x18\x03 \x03(\tR\vchildrenIds\x12\x1b\n" +
	"\tparent_id\x18\x04 \x01(\tR\bparentId\x123\n" +
	"\bfs_entry\x18\x05 \x01(\v2\x18.fs_tree_manager.FSEntryR\afsEntry\"\xba\x01\n" +
	"\n" +
	"MerkleTree\x12\x17\n" +
	"\aroot_id\x18\x01 \x01(\tR\x06rootId\x12<\n" +
	"\x05nodes\x18\x02 \x03(\v2&.fs_tree_manager.MerkleTree.NodesEntryR\x05nodes\x1aU\n" +
	"\n" +
	"NodesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.fs_tree_manager.MerkleNodeR\x05value:\x028\x01\">\n" +
	"\aFSEntry\x123\n" +
	"\bmetadata\x18\x01 \x01(\v2\x17.google.protobuf.StructR\bmetadata2\xae\x01\n" +
	"\rFSTreeManager\x12[\n" +
	"\fFetchReplica\x12$.fs_tree_manager.FetchReplicaRequest\x1a%.fs_tree_manager.FetchReplicaResponse\x12@\n" +
	"\fNewDirectory\x12\x18.fs_tree_manager.FSEntry\x1a\x16.google.protobuf.EmptyB\"Z github.com/puter/fs_tree_managerb\x06proto3"

var (
	file_fs_tree_manager_proto_rawDescOnce sync.Once
	file_fs_tree_manager_proto_rawDescData []byte
)

func file_fs_tree_manager_proto_rawDescGZIP() []byte {
	file_fs_tree_manager_proto_rawDescOnce.Do(func() {
		file_fs_tree_manager_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fs_tree_manager_proto_rawDesc), len(file_fs_tree_manager_proto_rawDesc)))
	})
	return file_fs_tree_manager_proto_rawDescData
}

var file_fs_tree_manager_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_fs_tree_manager_proto_goTypes = []any{
	(*FetchReplicaRequest)(nil),  // 0: fs_tree_manager.FetchReplicaRequest
	(*FetchReplicaResponse)(nil), // 1: fs_tree_manager.FetchReplicaResponse
	(*MerkleNode)(nil),           // 2: fs_tree_manager.MerkleNode
	(*MerkleTree)(nil),           // 3: fs_tree_manager.MerkleTree
	(*FSEntry)(nil),              // 4: fs_tree_manager.FSEntry
	nil,                          // 5: fs_tree_manager.MerkleTree.NodesEntry
	(*structpb.Struct)(nil),      // 6: google.protobuf.Struct
	(*emptypb.Empty)(nil),        // 7: google.protobuf.Empty
}
var file_fs_tree_manager_proto_depIdxs = []int32{
	3, // 0: fs_tree_manager.FetchReplicaResponse.tree:type_name -> fs_tree_manager.MerkleTree
	4, // 1: fs_tree_manager.MerkleNode.fs_entry:type_name -> fs_tree_manager.FSEntry
	5, // 2: fs_tree_manager.MerkleTree.nodes:type_name -> fs_tree_manager.MerkleTree.NodesEntry
	6, // 3: fs_tree_manager.FSEntry.metadata:type_name -> google.protobuf.Struct
	2, // 4: fs_tree_manager.MerkleTree.NodesEntry.value:type_name -> fs_tree_manager.MerkleNode
	0, // 5: fs_tree_manager.FSTreeManager.FetchReplica:input_type -> fs_tree_manager.FetchReplicaRequest
	4, // 6: fs_tree_manager.FSTreeManager.NewDirectory:input_type -> fs_tree_manager.FSEntry
	1, // 7: fs_tree_manager.FSTreeManager.FetchReplica:output_type -> fs_tree_manager.FetchReplicaResponse
	7, // 8: fs_tree_manager.FSTreeManager.NewDirectory:output_type -> google.protobuf.Empty
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_fs_tree_manager_proto_init() }
func file_fs_tree_manager_proto_init() {
	if File_fs_tree_manager_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fs_tree_manager_proto_rawDesc), len(file_fs_tree_manager_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fs_tree_manager_proto_goTypes,
		DependencyIndexes: file_fs_tree_manager_proto_depIdxs,
		MessageInfos:      file_fs_tree_manager_proto_msgTypes,
	}.Build()
	File_fs_tree_manager_proto = out.File
	file_fs_tree_manager_proto_goTypes = nil
	file_fs_tree_manager_proto_depIdxs = nil
}
