syntax = "proto3";

import "google/protobuf/struct.proto";
import "google/protobuf/empty.proto";

package fs_tree_manager;

option go_package = "github.com/puter/fs_tree_manager";

service FSTreeManager {
  rpc FetchReplica(UserName) returns (MerkleTree);
  rpc PullDiff(PullRequest) returns (PushRequest);

  // We provide simple New/Remove APIs as a straightforward way to accommodate
  // the wide variety of file system operations. For simplicity, these APIs do
  // not automatically update parent or child FSEntries.
  rpc NewFSEntry(FSEntry) returns (google.protobuf.Empty);
  rpc RemoveFSEntry(FSEntry) returns (google.protobuf.Empty);

  // For any fs operations that cannot be handled by New/Remove APIs, just purge
  // the replica.
  rpc PurgeReplica(UserName) returns (google.protobuf.Empty);
}

message UserName { string user_name = 1; }

message MerkleNode {
  // We use the stable uuid from fs_entry so pointers to it stay valid when this
  // node is updated.
  string uuid = 1;

  // We use string instead of uint64 for several reasons:
  // 1. JS is error prone when handling uint64/bigint and it's time-consuming to
  //    troubleshoot.
  // 2. It's easier to come up with a consistent order on string type.
  string merkle_hash = 2;

  repeated string children_uuids = 3;
  string parent_uuid = 4;

  FSEntry fs_entry = 5;
}

// The motivation of this design is elaborated in the RFC
// (doc/RFCS/20250821_client_replica_file_system.md)
message MerkleTree {
  string root_uuid = 1;

  // id -> node
  map<string, MerkleNode> nodes = 2;
}

message FSEntry { google.protobuf.Struct metadata = 1; }

message PullRequest {
  // user_name is always needed since replica are distinguished by user_name
  string user_name = 1;

  repeated PullRequestItem pull_request = 2;
}

message PullRequestItem {
  string uuid = 1;
  string merkle_hash = 2;
}

message PushRequest {
  // user_name is always needed since replica are distinguished by user_name
  string user_name = 1;

  repeated PushRequestItem push_request = 2;
}

message PushRequestItem {
  string uuid = 1;
  string merkle_hash = 2;
  FSEntry fs_entry = 3;
  repeated PushRequestItem children = 4;
}
